name: Build and Push Docker Image to Docker Hub

on:
 workflow_dispatch

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: elestio/yopass

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t my_image --rm=false --progress=plain  .
    - name: cat the output file
      run: | 
            wget https://github.com/aquasecurity/trivy/blob/main/contrib/html.tpl
            pwd
             
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      with:
         image-ref: my_image #'docker.io/my-organization/my-app:${{ github.sha }}'
         format: 'html'
         template: './html.tpl'
         output: 'trivy-results.html'
         severity: 'CRITICAL,HIGH'
     
    - name: cat the output file
      run: cat trivy-results.html

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
       sarif_file: 'trivy-results.sarif'

#   - name: Aqua Security Trivy
  # You may pin to the exact commit or the version.
  # uses: aquasecurity/trivy-action@41f05d9ecffa2ed3f1580af306000f734b733e54
      #  uses: aquasecurity/trivy-action@0.11.2
     #   with:
      # Scan type to use for scanning vulnerability
       #  scan-type: image
      # image reference(for backward compatibility)
        # image-ref: my_image
