---
name: build and push docker image
on: push
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          sudo chmod +x createimage.sh
          sudo ./createimage.sh
        shell: bash
