name: This workflow is to build docker image for java application.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch?? right condition or change required.
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#define variables
env:
  #add variables and values

jobs:
    sonarscan:
    runs-on: ubuntu-latest    
# Checks-out your repository under 
    uses: actions/checkout@v3
   
   # You may pin to the exact commit or the version.
# uses: SonarSource/sonarqub/e-scan-action@a6ba0aafc293e03de5437af7edbc97f7d3ebc91a
    uses: SonarSource/sonarqube-scan-action@v1.2.0
    with:
# Additional arguments to the sonar-scanner
      args: # optional
# Set the sonar.projectBaseDir analysis property
      projectBaseDir: # optional, default is .
