name: Build workflow Test variables

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - development

  workflow_dispatch:
    inputs:
        image_type:
            description: Image Type
            required: true
            type: choice
            default: native
            options:
              - native
